<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.2.2 setup script
 * Date: Sat, 31 May 2014 14:25:17 -0700
 */

/* Servers configuration */
$i = 0;

/* Server: vergil.u.washington.edu [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = ’vergil.u.washington.edu’;
$cfg['Servers'][$i]['port'] = 38733;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'mypassword';

/* End of servers configuration */

$cfg['blowfish_secret'] = '538a3d280e0269.71141112';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>