		<h2> test section header </h2>
		<!-- main page content -->
		<p>
		Hi there, how are you? Please login here:
		</p>
		<form action="handle_login.php" method="post">
		<p>User Name: <input type="text" name="username" size="20" /></p>
		<p>Password: <input type="password" name="username" size="20" /></p>
		<input type="submit" name="submit" value="Log Me In!" />
		</form>
		<p>
			Not registered? Click <a href="registration.php"> here</a> to do so!
		</p>

	