		<h2> test section header </h2>
		<!-- main page content -->
		<p>
		Hi there, how are you?
		</p>
		<form action="handle_registration.php" method="post">
		<p>User Name: <input type="text" name="username" size="20" /></p>
		<p>Password: <input type="password" name="password" size="20" /></p>
		<p>Repeat Password: <input type="password" name="r_password" size="20" /></p>
		<p>First Name: <input type="text" name="f_name" size="20" /></p>	
		<p>Last Name: <input type="text" name="l_name" size="20" /></p>
		<p>Email Addres: <input type="text" name="email" size="20" /></p>
		<p>Phone Number: <input type="text" name="phone" size="20" /></p>
		<input type="submit" name="submit" value="Register me!" />
		</form>
		<p>
			Already registered? Click <a href="login.php"> here</a> to login!
		</p>
